// Code generated by hertz generator.

package main

import (
	"derma/detect/config"
	"derma/detect/dal"
	aireq "derma/detect/pkg/ai_req"

	"github.com/cloudwego/hertz/pkg/app/server"
)

func Init() {
	config.InitConfig()
	dal.Init()
	aireq.Init()
}

func main() {
	Init()
	h := server.Default(
		server.WithHostPorts("0.0.0.0:18005"),
	)

	register(h)
	h.Spin()
}
