// Code generated by hertz generator.

package main

import (
	"derma/detect/config"
	"derma/detect/dal"

	"github.com/cloudwego/hertz/pkg/app/server"
)

func Init() {
	config.InitConfig()
	dal.Init()
}

func main() {
	Init()
	h := server.Default()

	register(h)
	h.Spin()
}
