// Code generated by hertz generator.

package api

import (
	"context"

	api "derma/detect/biz/model/api"
	"derma/detect/pack"

	"github.com/cloudwego/hertz/pkg/app"
)

// AIDoctor .
// @router /derma/detect/ai-doctor [GET]
func AIDoctor(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.AiDoctorRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, err)
		return
	}

	resp := new(api.AiDoctorResponse)

	pack.SendResponse(c, resp)
}
