// Code generated by hertz generator.

package api

import (
	"context"

	api "derma/detect/biz/model/api"
	"derma/detect/pack"
	"derma/detect/pkg/errno"
	"derma/detect/pkg/utils"
	service "derma/detect/service/user"
	user "derma/detect/service/user"

	"github.com/cloudwego/hertz/pkg/app"
)

// UserRegister .
// @router /derma/detect/user/register/ [POST]
func UserRegister(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.UserRegisterRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, err)
		return
	}

	resp := new(api.UserRegisterResponse)

	// 对传入的数据做判断
	if len(req.Username) == 0 || len(req.Username) > 255 || len(req.Password) == 0 || len(req.Password) > 255 {
		pack.SendFailResponse(c, errno.ParamError)
		return
	}

	// TODO:
	// 发给业务层
	userResp, err := user.NewUserService(ctx).CreateUser(&req)

	// 包装返回值
	if err != nil {
		pack.SendFailResponse(c, err)
		return
	}

	token, err := utils.CreateToken(userResp.Id)
	if err != nil {
		pack.SendFailResponse(c, err)
		return
	}

	resp.StatusCode, resp.StatusMsg = pack.BuildBaseResp(nil)
	resp.UserID = userResp.Id
	resp.Token = token

	pack.SendResponse(c, resp)
}

// UserLogin .
// @router /derma/detect/user/login/ [POST]
func UserLogin(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.UserLoginRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, err)
		return
	}

	resp := new(api.UserLoginResponse)

	if len(req.Username) == 0 || len(req.Username) > 255 || len(req.Password) == 0 || len(req.Password) > 255 {
		pack.SendFailResponse(c, errno.ParamError)
		return
	}

	userResp, err := service.NewUserService(ctx).CheckUser(&req)

	if err != nil {
		pack.SendFailResponse(c, err)
		return
	}

	token, err := utils.CreateToken(userResp.Id)

	if err != nil {
		pack.SendFailResponse(c, err)
		return
	}

	resp.StatusCode, resp.StatusMsg = pack.BuildBaseResp(nil)
	resp.UserID = userResp.Id
	resp.Token = token

	pack.SendResponse(c, resp)
}
