// Code generated by hertz generator.

package api

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _dermaMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _detectMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userloginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userregisterMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _historyMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userhistoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _infoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _reset_infoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _resetinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _reset_passwordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _resetpasswordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _pictureMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadpictureMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _upload_avatarMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadavatarMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _historyinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _info0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _aidoctorMw() []app.HandlerFunc {
	// your code...
	return nil
}
