services:
    mysql:
        container_name: mysql
        image: mysql:latest
        restart: always
        env_file:
            - "./env/mysql.env"
        volumes:
            - ../config/sql:/docker-entrypoint-initdb.d/
            - ./data/mysql:/var/lib/mysql
            - ../config/sql/my.cnf:/etc/my.cnf
        ports:
            - 3306:3306
        networks:
            - derma

networks:
    derma:
        driver: bridge
        name: derma